cookie:
  secret: 'REPLACE SECRET IN DEVELOPMENT.YAML'
session:
  secret: 'REPLACE SECRET IN DEVELOPMENT.YAML'
base:
    path: ''
run:
  host: 'localhost'
  port: 3000
  path: '/run'
nez:
    path: './nez/nez.jar'
    option: 'parse'
    env: ''
konoha:
    path: './konoha/konoha.jar'
    option: ''
    env: ''
